name: Release
on:
  push:
    branches:
      - main  # 或者你的默认分支名称

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    defaults:
      run:
        working-directory: ./pngme

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Run tests
        run: cargo test

      - name: Build release
        run: cargo build --release

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: Tag_${{ github.sha }}_${{ matrix.os }} 
          release_name: Release_${{ github.sha }}_${{ matrix.os }} 
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pngme/target/release/pngme  # 替换为你的实际应用程序路径和文件名
          asset_name: pngme-${{ matrix.os }}  # 替换为你的实际应用程序名称和文件名
          asset_content_type: application/octet-stream
