name: Release
on:
  push:
    branches:
      - main  # 或者你的默认分支名称

jobs:
  release:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./pngme

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Update rustup
        run: rustup update

      - name: Install target platform
        run: rustup target add x86_64-pc-windows-gnu

      - name: Install mingw-w64
        run: sudo apt-get install -y mingw-w64 

      - name: Run tests
        run: cargo test

      - name: Build releases
        id: build_releases
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          cargo build --release --target x86_64-pc-windows-gnu

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: Tag_${{ github.sha }}
          release_name: Release_${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pngme/target/x86_64-unknown-linux-gnu/release/pngme  # 替换为你的实际应用程序路径
          asset_name: pngme-x86_64-linux  # 替换为你的实际应用程序名称
          asset_content_type: application/octet-stream

       - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pngme/target/x86_64-pc-windows-gnu/release/pngme.exe  # 替换为你的实际应用程序路径
          asset_name: pngme-x86_64-pc-windows-gnu.exe  # 替换为你的实际应用程序名称
          asset_content_type: application/octet-stream

      

